{
  LinearLayout,
  layout_width="match_parent",
  layout_height="match_parent",
  baselineAligned=false,
  orientation="horizontal",
  {
    LinearLayout,
    layout_width="0dp",
    layout_height="wrap_content",
    layout_weight="1",
    gravity="center",
    orientation="vertical",
    {
      TextView,
      layout_width="wrap_content",
      layout_height="wrap_content",
      text="potrait",
    },
    {
      NumberPicker,
      id="portrait_columns",
      layout_width="wrap_content",
      layout_height="wrap_content",
      descendantFocusability=NumberPicker.FOCUS_BLOCK_DESCENDANTS,
      maxValue="7",
      minValue="0",
    },
  },
  {
    LinearLayout,
    layout_width="0dp",
    layout_height="wrap_content",
    layout_weight="1",
    gravity="center",
    orientation="vertical",
    {
      TextView,
      layout_width="wrap_content",
      layout_height="wrap_content",
      text="lanskap",
    },
    {
      NumberPicker,
      id="landscape_columns",
      layout_width="wrap_content",
      layout_height="wrap_content",
      descendantFocusability=NumberPicker.FOCUS_BLOCK_DESCENDANTS,
      maxValue="7",
      minValue="0",
    }
  }
}